# Generated by Django 3.2.15 on 2022-12-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(default='', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=170, verbose_name='Height')),
                ('current_weight', models.FloatField(default=70, verbose_name='Current Weight')),
                ('goal_weight', models.FloatField(default=57, verbose_name='Goal Weight')),
                ('email', models.EmailField(default='user@gmail.com', max_length=254, verbose_name='Email')),
                ('username', models.CharField(default='anonymous', max_length=100, unique=True, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
