# Generated by Django 3.2.15 on 2022-11-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('create_at', models.DateTimeField(auto_created=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=80)),
                ('age', models.IntegerField(blank=True)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
