# Generated by Django 3.2.15 on 2022-12-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default='anonymous', max_length=100, on_delete=django.db.models.deletion.PROTECT, to='main.user', to_field='username'),
        ),
    ]
